export const ActionReducer = {
    SET_PRELOAD: "SET_PRELOAD",

    SET_AUTH: "SET_AUTH",
    UNSET_AUTH: "UNSET_AUTH",

    SET_LOADING: "SET_LOADING",

    GET_ANTAM_GOLD_PRICE: "GET_ANTAM_GOLD_PRICE"
};

export enum ActionReducerType  {
    SET_PRELOAD = "SET_PRELOAD",

    SET_AUTH = "SET_AUTH",
    UNSET_AUTH = "UNSET_AUTH",

    SET_LOADING = "SET_LOADING",

    GET_ANTAM_GOLD_PRICE = "GET_ANTAM_GOLD_PRICE"
}
