export const ActionReducer = {
    SET_PRELOAD: "SET_PRELOAD",

    SET_AUTH: "SET_AUTH",
    UNSET_AUTH: "UNSET_AUTH",

    SET_LOADING: "SET_LOADING",

    SET_HOME_REFRESH: "SET_HOME_REFRESH",

    SET_CATEGORIES_SPEND: "SET_CATEGORIES_SPEND",
};

export enum ActionReducerType  {
    SET_PRELOAD = "SET_PRELOAD",

    SET_AUTH = "SET_AUTH",
    UNSET_AUTH = "UNSET_AUTH",

    SET_LOADING = "SET_LOADING",

    SET_HOME_REFRESH = "SET_HOME_REFRESH",

    SET_CATEGORIES_SPEND = "SET_CATEGORIES_SPEND",
}
